In [16]:
import numpy as np

In [17]:
a2 = np.random.randn(10,2)
exp_scores = np.exp(a2)
softmax = exp_scores / np.sum(exp_scores, axis = 1, keepdims = True)

In [18]:
print("a2:\n{}\n\nexp_scores:\n{}".format(a2,exp_scores))

a2:
[[ 0.86075567 -0.71749258]
 [ 1.09453135 -1.61940802]
 [ 1.3327194   1.64629836]
 [ 0.88783032 -1.26403245]
 [ 1.19555803 -0.28719065]
 [-0.22414358  0.62849449]
 [-1.62663261  0.772824  ]
 [-0.02647893 -0.71145685]
 [ 1.31571456  0.30207522]
 [-0.13737358  0.03035951]]

exp_scores:
[[2.36494714 0.48797428]
 [2.98778212 0.19801589]
 [3.79133955 5.1877411 ]
 [2.42985193 0.28251251]
 [3.30540178 0.75036866]
 [0.79920038 1.87478595]
 [0.19659046 2.16587405]
 [0.97386856 0.49092847]
 [3.72741349 1.35266297]
 [0.87164453 1.03082506]]


In [19]:
np.sum(exp_scores, axis = 1)  #shape(10,1)

array([2.85292142, 3.185798  , 8.97908064, 2.71236444, 4.05577044,
       2.67398633, 2.36246451, 1.46479703, 5.08007646, 1.9024696 ])

In [20]:
np.sum(exp_scores, axis = 1, keepdims = True) #keepdims=True to keep it 2-dimensional

array([[2.85292142],
       [3.185798  ],
       [8.97908064],
       [2.71236444],
       [4.05577044],
       [2.67398633],
       [2.36246451],
       [1.46479703],
       [5.08007646],
       [1.9024696 ]])

In [21]:
softmax = exp_scores / np.sum(exp_scores, axis = 1, keepdims = True)
softmax

array([[0.82895628, 0.17104372],
       [0.93784418, 0.06215582],
       [0.4222414 , 0.5777586 ],
       [0.89584272, 0.10415728],
       [0.81498739, 0.18501261],
       [0.29887975, 0.70112025],
       [0.08321414, 0.91678586],
       [0.66484881, 0.33515119],
       [0.73373177, 0.26626823],
       [0.45816476, 0.54183524]])

NumPy recognizes that the shapes of ***exp_scores*** and the result of the sum operation are not the same, 
but they are compatible for *broadcasting*. So, when we perform the division ***exp_scores / np.sum(exp_scores, axis=1, keepdims=True)***, NumPy broadcasts the sum result to have a shape of (10, 2), which matches the shape of ***exp_scores***, and then performs element-wise division, yielding a result of shape (10, 2), as expected.

In [22]:
y = np.array([0, 1, 0, 1, 1, 0, 0, 1, 1, 0])
y

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 0])

In [23]:
# it extracts out the predicted values of the expected class
m = np.zeros(10)
for i,correct_index in enumerate(y):
    predicted = softmax[i][correct_index]
    m[i] = predicted
m

array([0.82895628, 0.06215582, 0.4222414 , 0.10415728, 0.18501261,
       0.29887975, 0.08321414, 0.33515119, 0.26626823, 0.45816476])

In [24]:
np.argmax(softmax, axis=1)  #returns the idex number where maximum occurs

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 1], dtype=int64)